name: agendadoradmin
description: "Agendamento para barbearia"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  universal_html: ^2.2.4
  font_awesome_flutter: ^10.9.1
  data_table_2: ^2.6.0
  flutter_secure_storage: ^9.2.4
  go_router: ^14.8.1
  provider: ^6.1.5+1
  dropdown_button2: ^2.3.9
  http: ^1.2.2
  file_picker: ^10.3.3
  flutter_multi_formatter: ^2.13.0
  mask_text_input_formatter: ^2.9.0
  shared_preferences: ^2.2.0
  intl: ^0.20.1
  fluttertoast: ^8.2.8
  cpf_cnpj_validator: ^2.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/